### ISSUE TITLE
not working after 4/30/2019 update 

### ISSUE THREAD

**Issue by rpkaul** [b3none/retakes-autoplant#1] opened 2019-05-01 04:31 UTC
i am getting this error in in-game console 

L 05/01/2019 - 09:59:26: [SM] Exception reported: Failed to lookup CSWeaponDropBB signature.
L 05/01/2019 - 09:59:26: [SM] Blaming: retakes_autoplant.smx
L 05/01/2019 - 09:59:26: [SM] Call stack trace:
L 05/01/2019 - 09:59:26: [SM]   [0] CS_DropWeapon
L 05/01/2019 - 09:59:26: [SM]   [1] Line 153, retakes_autoplant.sp::SafeRemoveWeapon
L 05/01/2019 - 09:59:26: [SM]   [2] Line 63, retakes_autoplant.sp::OnRoundStart
L 05/01/2019 - 09:59:26: [SM]   [4] ServerCommandEx
L 05/01/2019 - 09:59:26: [SM]   [5] Line 400, /home/builds/sourcemod/linux-1.9/build/plugins/basecommands.sp::Command_Rcon

**Comment by B3none** [comment] 2019-05-01 04:59
Thanks for taking the time to submit this issue! I’ll have a look into it later on today and ideally get a fix rolled out.

https://github.com/b3none/retakes-autoplant/issues/1#issuecomment-488212463

**Comment by brianando** [comment] 2019-05-01 05:12
Same issue here :(

L 05/01/2019 - 05:11:07: [SM] Exception reported: Failed to lookup CSWeaponDropBB signature.
L 05/01/2019 - 05:11:07: [SM] Blaming: retakes_autoplant.smx
L 05/01/2019 - 05:11:07: [SM] Call stack trace:
L 05/01/2019 - 05:11:07: [SM]   [0] CS_DropWeapon
L 05/01/2019 - 05:11:07: [SM]   [1] Line 153, retakes_autoplant.sp::SafeRemoveWeapon
L 05/01/2019 - 05:11:07: [SM]   [2] Line 63, retakes_autoplant.sp::OnRoundStart

**Comment by 3GaNwO** [comment] 2019-05-01 05:13
I am having the same errors 

Linux servers
SM Version: 1.9

-OwNaG3

**Comment by B3none** [comment] 2019-05-01 05:15
Hey guys, you’re going to need to update your gamedata. If you’re not sure how to do this here’s a link to a guide:
https://github.com/splewis/csgo-pug-setup/wiki/Frequently-Asked-Questions#issues-after-a-csgo-update-aka-help-a-csgo-update-broke-the-mod

Here’s a link to the relevant sourcemod pull request: https://github.com/alliedmodders/sourcemod/pull/985/files

**Comment by Fohdeesha** [comment] 2019-05-01 06:40
looks like it was just merged, I can't pull it via auto gamedata updates and it's not in the latest dev build yet on sourcemod downloads: https://www.sourcemod.net/downloads.php?branch=dev

I'm not sure when those builds happen, but whenever the next one is it should be good to go, sometime today

**Comment by Fohdeesha** [comment] 2019-05-01 08:54
looks like the autobuild including the above merge failed so it's not downloadable, so I manually copied in the new gamedata by saving https://raw.githubusercontent.com/alliedmodders/sourcemod/master/gamedata/sm-cstrike.games/game.csgo.txt

into the server folder: /go/csgo/addons/sourcemod/gamedata/sm-cstrike.games/

at this point sourcemod detected it as out-of-date gamedata and overwrote it with the old (broken) file, so I set DisableAutoUpdate to "yes" in core.cfg to prevent it from doing so. It now loads the new gamedata from what I can tell, but I still get the error in the original post. Are their other SM commits I need?

**Comment by Fohdeesha** [comment] 2019-05-01 09:03
According to the commit comments, it looks like it was still failing because the new signatures are actually still broken: https://github.com/alliedmodders/sourcemod/pull/985

**Comment by B3none** [comment] 2019-05-01 09:15
Looks like it's just a case of waiting it out I'm afraid:
https://forums.alliedmods.net/showthread.php?t=315901

I'd suggest joining the SourceMod discord to keep up to date:
https://discord.gg/h4tZmVa

**Comment by p3net** [comment] 2019-05-01 16:27
Any Updates?

**Comment by shmidtelson** [comment] 2019-05-01 19:59
> Any Updates?

yes! download plugin and compile

**Comment by PerfectLaugh** [comment] 2019-05-01 20:06
> > Any Updates?
> 
> yes! download plugin and compile

That won't help. The problem is in Sourcemod.

**Comment by p3net** [comment] 2019-05-01 20:13
> > > Any Updates?
> > 
> > 
> > yes! download plugin and compile
> 
> That won't help. The problem is in Sourcemod.

Yeah just recompiled it. but i guess well just have to wait

**Comment by 3GaNwO** [comment] 2019-05-01 20:18
You will need to update Sourcemod to the latest release and then with this new plugin that was compiled 30 mins ago it should run perfectly.

I have gone ahead and tested this on my Linux servers I run about 8 retake servers and with Sourcemod up to date and this new compile of the plugin it seems to run just as it did before! 

Hope that helps and thank you B3 for making the update (:

**Comment by B3none** [comment] 2019-05-01 20:34
Compile the latest `retakes_autoplant.sp` as instructed above.

**Comment by rpkaul** [comment] 2019-05-01 21:05
Recompiled new sourcecode with updated sourcemod working fine for me
Tysm for update b3none

**Closed as completed** 2019-05-01 21:11 UTC
